1.0.0-beta.19

diff --git a/bin/publish-version b/bin/publish-version
--- a/bin/publish-version
+++ b/bin/publish-version
@@ -23,6 +23,14 @@ if [[ $BRANCH != 'develop' ]]; then
   git checkout develop
 fi
 
+yarn lint:fix
+if [[ $? != 0 ]]; then
+  echo
+  echo "Fix yo lint errors"
+  echo
+  exit 1
+fi
+
 yarn build
 
 if [[ $? != 0 ]]; then
